# Main entrypoint of the workflow. 
# Please follow the best practices: 
# https://snakemake.readthedocs.io/en/stable/snakefiles/best_practices.html,
# in particular regarding the standardized folder structure mentioned there. 

import os

CONFIG = 'config/gwm-arc-config.yml'
configfile: CONFIG

# include: 'Snakefile_0'

rule all:
    input:
        'results/regrid_filenames.txt'

rule regrid_jules_output:
    input:
        script='workflow/scripts/regrid-jules-output.py',
        config=CONFIG
    output:
        'results/regrid_filenames.txt'
    params:
        None
    resources:
        time = "00:30:00",
        mem_mb = 4000,
        partition = "short"
    conda:
        'esmvaltool'
    shell:
        """
        export PYTHONPATH=
        python {input.script} -o {output} --config {input.config}
        """

rule aggregate_jules_output_month:
    input:
        regrid_filenames='results/regrid_filenames.txt',
        script='workflow/scripts/aggregate-jules-output.py',
        config=CONFIG
    output:
        'results/aggregate_filenames.txt'
    params:
        period='month'
    resources:
        time = "00:30:00",
        mem_mb = 4000,
        partition = "short"
    conda:
        'esmvaltool'
    shell:
        """
        export PYTHONPATH=
        python {input.script} -i {input.regrid_filenames} -o {output} --period {params.period} --config {input.config}
        """

rule aggregate_jules_output_year:
    input:
        regrid_filenames='results/regrid_filenames.txt',
        script='workflow/scripts/aggregate-jules-output.py',
        config=CONFIG
    output:
        'results/aggregate_filenames.txt'
    params:
        period='year'
    resources:
        time = "00:30:00",
        mem_mb = 4000,
        partition = "short"
    conda:
        'esmvaltool'
    shell:
        """
        export PYTHONPATH=
        python {input.script} -i {input.regrid_filenames} -o {output} --period {params.period} --config {input.config}
        """

# rule all:
#     input:
#         expand('results/exp1/fig/{aggr_plot}', aggr_plot = AGGR_PLOT)

# rule select_stations:
#     input:
#         script='workflow/scripts/select-stations-exp1.R',
#         config=CONFIG
#     output:
#         STATIONS_FILE
#     params:
#         outfile=STATIONS_FILE
#     resources:
#         time = "00:30:00",
#         mem_mb = 4000,
#         partition = "short"
#     shell:
#         """
#         Rscript {input.script} {config[input_data_root]} {params.outfile} {input.config}
#         """
