jules:
  name:
  start_year: 1979
  end_year: 2014
  suite: u-ci496
  id_stem:
    - JULES_vn6.1_irrig_current
    - JULES_vn6.1_irrig
    - JULES_vn6.1_noirrig
  job_name: jules_{year}
  profile_name: daily_hydrology
  jules_output_directory: /data/ouce-drift/cenv0857/JULES_output/u-ci496
  gridfile: /data/ouce-drift/cenv0857/ganges_water_machine_data/wfdei/ancils/WFD-EI-LandFraction2d_igp.nc
  y_dim_name: lat
  x_dim_name: lon
  mask_var_name: lsmask
  soil_dim_name: soil
  tile_dim_name: dim0
  pft_dim_name: dim1

regrid_jules_output:
  output_directory: /data/ouce-drift/cenv0857/ganges_water_machine_data/jules-output/u-ci496
  file_suffix: 2D

resample_jules_output:
  input_directory: /home/sm510/projects/ganges_water_machine/jules-output/u-ci496
  output_directory: /home/sm510/projects/ganges_water_machine/jules-output/u-ci496
  xmin: 60
  xmax: 100
  ymin: 20
  ymax: 40
  resolution: 15min
  input_file_suffix: 2D
  output_file_suffix: 2D.regrid

aggregate_jules_output:
  input_directory: /home/sm510/projects/ganges_water_machine/jules-output/u-ci496
  output_directory: /home/sm510/projects/ganges_water_machine/jules-output/u-ci496
  input_file_suffix: 2D

annual_mean_runoff:
  input_directory: /home/sm510/projects/ganges_water_machine/jules-output/u-ci496
  input_file_suffix: 2D.regrid
  output_filename: /home/sm510/projects/ganges_water_machine/jules-output/u-ci496/jules_ann_mean_1979_2014_regrid.nc

combined_runoff:
  input_directory: /home/sm510/projects/ganges_water_machine/jules-output/u-ci496
  input_file_suffix: 2D.regrid
  output_filename: /home/sm510/projects/ganges_water_machine/mosart-input/jules_runoff_1979_2014.nc

mosart:
  merit_hydro_directory: /home/sm510/data/MERIT/hydro
  merit_ihu_directory: /mnt/scratch/scratch/data/MERIT_IHU
  geomorpho90m_directory: /home/sm510/data/geomorpho90m
  aux_directory: aux
  mean_annual_runoff: /home/sm510/projects/ganges_water_machine/jules-output/u-ci496/jules_ann_mean_1979_2014_regrid.nc
  mean_annual_runoff_varname: runoff
  xmin: 60
  xmax: 100
  ymin: 20
  ymax: 40
  resolution: 15min
  outlet_x: 87.875
  outlet_y: 25.125
  merit_scale_factor: 300
  grass_location: /home/sm510/grassdata/latlong
  grass_mapset: mosart
  input_directory: /home/sm510/projects/ganges_water_machine/jules-output
  input_file_suffix: 2D.regrid
  output_directory: /home/sm510/projects/ganges_water_machine/mosart-input
